### ISSUE TITLE
Savoir gérer la déconnection côté client

### ISSUE THREAD

**Issue by GabrielWink** [Stormancer/stormancer-sdk-as3#1]
- Pouvoir se déconnecter manuellement côté client (une fonction genre scene.Disconnect(reason:String) ).
- Actuellement une déco côté serveur provoque une erreur dans le client (ligne 51 de DefaultDispatcher.as)
- Toujours recevoir un évènement lorsqu'on est déconnecté, qui indique la raison (celle envoyé par le serveur si c'est lui qui nous a déconnecté intentionnellement, ou une info si c'est une déco accidentelle).

**Comment by Falanwe** [comment]
Disconnection handling has been added in the latest version
