### ISSUE TITLE
La trace est coupée en cas d'exception dans OnConnecting, OnConnected et Disconnected

### ISSUE THREAD

**Issue by GabrielWink** [Stormancer/stormancer-sdk-as3#2]
Et c'est assez ennuyeux pour trouver l'origine des bugs

**Comment by jmderuty** [comment]
Tu peux préciser ce que tu entends exactement par trace?

**Comment by GabrielWink** [comment]
La stack trace :)
En gros dans les logs, la liste d'appel qui décrit l'exception ne remonte pas jusqu'à l'endroit où l'exception s'est vraiment produite.
C'est ce que tu m'avais dit quand j'avais signalé ce bug (qui m'arrive occasionnellement encore, et je sais toujours pas pourquoi) : 
https://images.discordapp.net/.eJwNzMERgyAQAMBeKAA88MDYRgpwCDKnjgjDna9Meo_ffexX3f1Us9pEGs_GrDun2lfNUnukrKlWOnNsO-tUi4kiMW0lX8LGOudxBHyB9YPz4zQ8hOADBEBAiza4YD43Le8nK_FKueujkfr9AQNLJXU.VcwpBXUXmVmp4nN4RTVhtxihiPE

**Comment by Falanwe** [comment]
This bug appears to have been corrected in the current version of the host. The useful part of the stack trace appears now in the InnerExceptions property of the relevant AggregateException.
