### ISSUE TITLE
Croisement de packets lors de l'envoi du serveur vers le client.

### ISSUE THREAD

**Issue by GabrielWink** [Stormancer/stormancer-sdk-as3#6]
Côté serveur on a quelque chose comme : 
MyMethode()
{
client.Send("route1",  data1);
client.Broadcast("route2", data2);
}

Et côté client, il va parfois arriver que route2 soit appelé avant route1.
Je suis sûr du problème à 98% seulement, donc si vous voyez vraiment pas d'où ça peut venir je vais essayer de le traquer plus précisément.

**Comment by GabrielWink** [comment]
Après des recherches j'ai du neuf, je copie ce que j'ai envoyé via discord :

J'ai des précisions sur l'inversion de message. J'ai réussi à créer un exemple à peu près reproductible, et j'ai remarqué deux choses : 
- D'abord cet exemple a lieu quand on reçoit des messages d'une scène à laquelle on est en train de se connecter (envoyé dans l'evt onconnect)
- Ensuite, en rajoutant des messages, j'ai vu que c'était pas juste 2 qui arrivaient dans le désordre, c'est qu'ils arrivaient dans l'ordre exactement contraire à celui envoyé. En gros si j'envoie des messages 1, 2, 3 et 4 depuis le serveur, lorsque le bug se produit je vais recevoir 4, 3, 2, 1.
En fouillant un peu, ma suggestion est qu'il y a un buffer qui déconne dans le client. Je soupçonne celui de la fonction addScene de SceneDispatcher, qui, j'ai l'impression, stocke les message puis les ressort avec un pop() là où faudrait peut-être un shift().
Ce n'est qu'une supposition, parce que je comprend pas le code dans son ensemble, mais voilà, j'espère que ça aidera.

**Comment by Falanwe** [comment]
Stupid rookie mistake: a pop() instead of a shift(), so messages coming before the scene was properly connected appeared to arrive in reverse order.
