### ISSUE TITLE
Correction mineures dans SceneDispatcher.as

### ISSUE THREAD

**Issue by GabrielWink** [Stormancer/stormancer-sdk-as3#7]
Line 43 :  "if (buffer == null)", plutôt que "if (buffer != null)" (sinon ça n'a pas de sens)
Line 70 : "buffer.shift()", plutôt que "buffer.pop()" (sinon le buffer recrache les paquets dans l'ordre inverse duquel il les a reçu, et c'est mal.

**Comment by Falanwe** [comment]
Thanks for the fix!
